# default config.yml
names_path: D:\Minecraft\sev\dev\src\main\resources\NAMES.txt
plan_path: D:\Minecraft\sev\dev\src\main\resources\PLAN.txt
chat_data_path: D:\Minecraft\sev\dev\src\main\resources\CHAT_DATA.txt
fakes_path: D:\Minecraft\sev\YW5lite_Sev_Test\plugins\FakePlayer\fakes.json