# default config.yml
names_path: D:\Minecraft\sev\dev\src\main\resources\NAMES.txt
plan_path: D:\Minecraft\sev\dev\src\main\resources\PLAN.txt
chat_data_path: D:\Minecraft\sev\dev\src\main\resources\CHAT_DATA.txt